apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: scheduler
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:5060"
  # Consul 基础配置
  CONSULCONFIG__SERVICENAME: "SchedulerJobCenter"
  CONSULCONFIG__SERVICEIP: "scheduler-svc.scheduler.svc.cluster.local"
  CONSULCONFIG__SERVICEPORT: "5060"
  CONSULCONFIG__REGISTRYADDRESS: "http://consul-server.consul.svc.cluster.local:8500"
